export const funcionariosMock = [
  {
    id: 1,
    nome: "Ana Souza",
    cpf: "123.456.789-01",
    setor: "Padaria",
    status: "ativo",
    armario: "F02",
  },
  {
    id: 2,
    nome: "Paula Rocha",
    cpf: "234.567.890-12",
    setor: "Frente de Caixa",
    status: "ativo",
    armario: "F03",
  },
  {
    id: 3,
    nome: "Mariana Costa",
    cpf: "345.678.901-23",
    setor: "Hortifruti",
    status: "ativo",
    armario: "F04",
  },
  {
    id: 4,
    nome: "Carlos Mendes",
    cpf: "456.789.012-34",
    setor: "Açougue",
    status: "ativo",
    armario: "M02",
  },
  {
    id: 5,
    nome: "Joana Ferreira",
    cpf: "567.890.123-45",
    setor: "Padaria",
    status: "ativo",
    armario: null,
  },
  {
    id: 6,
    nome: "Marcos Alves",
    cpf: "678.901.234-56",
    setor: "Reposição",
    status: "ativo",
    armario: null,
  },
];