export const achadosPerdidosMock = [
  {
    id: 1,
    codigo: "AP-001",
    objeto: "Mochila preta",
    descricao: "Mochila escolar preta com alças largas",
    local: "Vestiário Feminino",
    data: "2026-09-10",
    status: "entregue",
    emoji: "📦",
  },
  {
    id: 2,
    codigo: "AP-002",
    objeto: "Garrafa térmica",
    descricao: "Garrafa azul 500ml com tampa vermelha",
    local: "Vestiário Masculino",
    data: "2026-09-11",
    status: "encontrado",
   emoji: "📦",
  },
  {
    id: 3,
    codigo: "AP-003",
    objeto: "Carteira",
    descricao: "Carteira marrom com documentos e cartões",
    local: "Armário F03",
    data: "2026-09-12",
    status: "entregue",
    emoji: "📦",
  },
  {
    id: 4,
    codigo: "AP-004",
    objeto: "Guarda-chuva",
    descricao: "Guarda-chuva preto dobrável",
    local: "Entrada do vestiário",
    data: "2026-09-13",
    status: "encontrado",
    emoji: "📦",
  },
  {
    id: 5,
    codigo: "AP-005",
    objeto: "Óculos de grau",
    descricao: "Armação preta, sem estojo",
    local: "Vestiário Feminino",
    data: "2026-09-14",
    status: "entregue",
    emoji: "📦",
  },
  {
    id: 6,
    codigo: "AP-006",
    objeto: "Chave avulsa",
    descricao: "Chave simples sem identificação",
    local: "Corredor dos armários",
    data: "2026-09-15",
    status: "encontrado",
    emoji: "📦",
  },
];